<?php

return [

    'feed_type' => [
        1 => 'New Post',
        2 => 'New Achievement',
        3 => 'New Poll',
    ],

    'feedcomment_post' => [
        'primary' => [
            'Nice',
            'Congrats',
            'More',
        ],
        'title' => [
            'Congratulations',
            'Wishes',
            'Acknowledgments',
        ],
        'list_one' => [
            "🎊🎉“Congratulations and BRAVO!”🎊🎉",
            "This calls for celebrating! Congratulations!",
            "You did it!🥳",
            "I knew it was only a matter of time. Well done!",
            "A mountain of greatness awaits you 😄",
            "Congratulations you're awesome!😊",
            "Attaboy",
            "Attagirl",
            "Hooray!!",
            "So thrilled for you 😁",
            "Hats off to you 🤠",
            "Congratulations! You nailed it!",
        ],
        'list_two' => [
            "🎉Happy birthday🎉",
            "Many more happy returns of the day!",
            "Time to party, it's your birthday!",
            "Wishing you the best of times ahead",
            "Wishing you success in all your endeavours",
            "Best of luck!",
            "All the best!",
            "Do well",
        ],
        'list_three' => [
            "Okay, thanks.",
            "That’s so cool",
            "Nice article",
            "Noted",
            "Thank you for sharing",
            "Agreed.",
            "Seconded.",
            "Information received",
            "Admirable efforts",
            "Informative!",
        ],
    ],

    'feedcomment_archivement' => [
        'primary' => [
            'Good job',
            'Congrats',
            'More',
        ],
        'title' => [
            'Appreciation',
            'Congratulations',
            'Wishes',
        ],
        'list_one' => [
            "I appreciate you 🤝",
            "You are an inspiration!",
            "I'm proud of you!",
            "That’s excellent!",
            "Much appreciated :)",
            "That’s a great accomplishment 🎉",
            "✨ True potential at its best ✨",
            "Good job🤝",
            "Good for you😄",
            "That’s amazing!",
            "Keep up the good work 🥳",
            "Good show🤗",
            "Nicely done 👍",
            "Way to go🤩",
        ],
        'list_two' => [
            "🎊🎉“Congratulations and BRAVO!”🎊🎉",
            "This calls for celebrating! Congratulations!",
            "You did it!🥳",
            "I knew it was only a matter of time. Well done!",
            "A mountain of greatness awaits you 😄",
            "Congratulations you're awesome!😊",
            "Attaboy",
            "Attagirl",
            "Hooray!!",
            "So thrilled for you 😁",
            "Hats off to you 🤠",
            "Congratulations! You nailed it!",
        ],
        'list_three' => [
            "🎉Happy birthday🎉",
            "Many more happy returns of the day!",
            "Time to party, it's your birthday!",
            "Wishing you the best of times ahead",
            "Wishing you success in all your endeavours",
            "Best of luck!",
            "All the best!",
            "Do well",
        ],
    ],

    'feedcomment_poll' => [
        'primary' => [
            'Nice',
            'Good show',
            'More',
        ],
        'title' => [
            'Appreciation',
            'Congratulations',
            'Wishes',
        ],
        'list_one' => [
            "Okay, thanks.",
            "That’s so cool",
            "Nice article",
            "Noted",
            "Thank you for sharing",
            "Agreed.",
            "Seconded.",
            "Information received",
            "Admirable efforts",
            "Informative!",
        ],
        'list_two' => [
            "I appreciate you 🤝",
            "You are an inspiration!",
            "I'm proud of you!",
            "That’s excellent!",
            "Much appreciated :)",
            "That’s a great accomplishment 🎉",
            "✨ True potential at its best ✨",
            "Good job🤝",
            "Good for you😄",
            "That’s amazing!",
            "Keep up the good work 🥳",
            "Good show🤗",
            "Nicely done 👍",
            "Way to go🤩",
        ],
        'list_three' => [
            "🎊🎉“Congratulations and BRAVO!”🎊🎉",
            "This calls for celebrating! Congratulations!",
            "You did it!🥳",
            "I knew it was only a matter of time. Well done!",
            "A mountain of greatness awaits you 😄",
            "Congratulations you're awesome!😊",
            "Attaboy",
            "Attagirl",
            "Hooray!!",
            "So thrilled for you 😁",
            "Hats off to you 🤠",
            "Congratulations! You nailed it!",
        ],
    ],

    'sticker_category' => [
        1 => 'Acknowledge',
        2 => 'Congrats',
        3 => 'Wishes',
    ],
];
